//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", IsNullable = false)]
public partial class status
{

    private string orderstatusField;

    private string shippingstatusField;

    private string confirmationstatusField;

    private string paymentstatusField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order-status")]
    public string orderstatus
    {
        get
        {
            return this.orderstatusField;
        }
        set
        {
            this.orderstatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-status")]
    public string shippingstatus
    {
        get
        {
            return this.shippingstatusField;
        }
        set
        {
            this.shippingstatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("confirmation-status")]
    public string confirmationstatus
    {
        get
        {
            return this.confirmationstatusField;
        }
        set
        {
            this.confirmationstatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("payment-status")]
    public string paymentstatus
    {
        get
        {
            return this.paymentstatusField;
        }
        set
        {
            this.paymentstatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
[System.Xml.Serialization.XmlRootAttribute("custom-attributes", Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", IsNullable = false)]
public partial class customattributes
{

    private customattributesCustomattribute[] customattributeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("custom-attribute", IsNullable = true)]
    public customattributesCustomattribute[] customattribute
    {
        get
        {
            return this.customattributeField;
        }
        set
        {
            this.customattributeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class customattributesCustomattribute
{

    private string attributeidField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("attribute-id")]
    public string attributeid
    {
        get
        {
            return this.attributeidField;
        }
        set
        {
            this.attributeidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", IsNullable = false)]
public partial class totals
{

    private totalsMerchandizetotal[] merchandizetotalField;

    private totalsAdjustedmerchandizetotal[] adjustedmerchandizetotalField;

    private totalsShippingtotal[] shippingtotalField;

    private totalsAdjustedshippingtotal[] adjustedshippingtotalField;

    private totalsShipmenttotal[] shipmenttotalField;

    private totalsOrdertotal[] ordertotalField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchandize-total")]
    public totalsMerchandizetotal[] merchandizetotal
    {
        get
        {
            return this.merchandizetotalField;
        }
        set
        {
            this.merchandizetotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adjusted-merchandize-total")]
    public totalsAdjustedmerchandizetotal[] adjustedmerchandizetotal
    {
        get
        {
            return this.adjustedmerchandizetotalField;
        }
        set
        {
            this.adjustedmerchandizetotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-total")]
    public totalsShippingtotal[] shippingtotal
    {
        get
        {
            return this.shippingtotalField;
        }
        set
        {
            this.shippingtotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adjusted-shipping-total")]
    public totalsAdjustedshippingtotal[] adjustedshippingtotal
    {
        get
        {
            return this.adjustedshippingtotalField;
        }
        set
        {
            this.adjustedshippingtotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipment-total")]
    public totalsShipmenttotal[] shipmenttotal
    {
        get
        {
            return this.shipmenttotalField;
        }
        set
        {
            this.shipmenttotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order-total")]
    public totalsOrdertotal[] ordertotal
    {
        get
        {
            return this.ordertotalField;
        }
        set
        {
            this.ordertotalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class totalsMerchandizetotal
{

    private string netpriceField;

    private string taxField;

    private string grosspriceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("net-price")]
    public string netprice
    {
        get
        {
            return this.netpriceField;
        }
        set
        {
            this.netpriceField = value;
        }
    }

    /// <remarks/>
    public string tax
    {
        get
        {
            return this.taxField;
        }
        set
        {
            this.taxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gross-price")]
    public string grossprice
    {
        get
        {
            return this.grosspriceField;
        }
        set
        {
            this.grosspriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class totalsAdjustedmerchandizetotal
{

    private string netpriceField;

    private string taxField;

    private string grosspriceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("net-price")]
    public string netprice
    {
        get
        {
            return this.netpriceField;
        }
        set
        {
            this.netpriceField = value;
        }
    }

    /// <remarks/>
    public string tax
    {
        get
        {
            return this.taxField;
        }
        set
        {
            this.taxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gross-price")]
    public string grossprice
    {
        get
        {
            return this.grosspriceField;
        }
        set
        {
            this.grosspriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class totalsShippingtotal
{

    private string netpriceField;

    private string taxField;

    private string grosspriceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("net-price")]
    public string netprice
    {
        get
        {
            return this.netpriceField;
        }
        set
        {
            this.netpriceField = value;
        }
    }

    /// <remarks/>
    public string tax
    {
        get
        {
            return this.taxField;
        }
        set
        {
            this.taxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gross-price")]
    public string grossprice
    {
        get
        {
            return this.grosspriceField;
        }
        set
        {
            this.grosspriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class totalsAdjustedshippingtotal
{

    private string netpriceField;

    private string taxField;

    private string grosspriceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("net-price")]
    public string netprice
    {
        get
        {
            return this.netpriceField;
        }
        set
        {
            this.netpriceField = value;
        }
    }

    /// <remarks/>
    public string tax
    {
        get
        {
            return this.taxField;
        }
        set
        {
            this.taxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gross-price")]
    public string grossprice
    {
        get
        {
            return this.grosspriceField;
        }
        set
        {
            this.grosspriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class totalsShipmenttotal
{

    private string netpriceField;

    private string taxField;

    private string grosspriceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("net-price")]
    public string netprice
    {
        get
        {
            return this.netpriceField;
        }
        set
        {
            this.netpriceField = value;
        }
    }

    /// <remarks/>
    public string tax
    {
        get
        {
            return this.taxField;
        }
        set
        {
            this.taxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gross-price")]
    public string grossprice
    {
        get
        {
            return this.grosspriceField;
        }
        set
        {
            this.grosspriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class totalsOrdertotal
{

    private string netpriceField;

    private string taxField;

    private string grosspriceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("net-price")]
    public string netprice
    {
        get
        {
            return this.netpriceField;
        }
        set
        {
            this.netpriceField = value;
        }
    }

    /// <remarks/>
    public string tax
    {
        get
        {
            return this.taxField;
        }
        set
        {
            this.taxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gross-price")]
    public string grossprice
    {
        get
        {
            return this.grosspriceField;
        }
        set
        {
            this.grosspriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", IsNullable = false)]
public partial class orders
{

    private object[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("custom-attributes", typeof(customattributes))]
    [System.Xml.Serialization.XmlElementAttribute("order", typeof(ordersOrder))]
    [System.Xml.Serialization.XmlElementAttribute("status", typeof(status))]
    [System.Xml.Serialization.XmlElementAttribute("totals", typeof(totals))]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class ordersOrder
{

    private string orderdateField;

    private string createdbyField;

    private string originalordernoField;

    private string currencyField;

    private string customerlocaleField;

    private string taxationField;

    private string invoicenoField;

    private string currentordernoField;

    private ordersOrderCustomer[] customerField;

    private status[] statusField;

    private ordersOrderProductlineitemsProductlineitem[] productlineitemsField;

    private ordersOrderShippinglineitemsShippinglineitem[] shippinglineitemsField;

    private ordersOrderShipmentsShipment[] shipmentsField;

    private totals[] totalsField;

    private ordersOrderPaymentsPayment[] paymentsField;

    private customattributesCustomattribute[] customattributesField;

    private string ordernoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order-date")]
    public string orderdate
    {
        get
        {
            return this.orderdateField;
        }
        set
        {
            this.orderdateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("created-by")]
    public string createdby
    {
        get
        {
            return this.createdbyField;
        }
        set
        {
            this.createdbyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("original-order-no")]
    public string originalorderno
    {
        get
        {
            return this.originalordernoField;
        }
        set
        {
            this.originalordernoField = value;
        }
    }

    /// <remarks/>
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-locale")]
    public string customerlocale
    {
        get
        {
            return this.customerlocaleField;
        }
        set
        {
            this.customerlocaleField = value;
        }
    }

    /// <remarks/>
    public string taxation
    {
        get
        {
            return this.taxationField;
        }
        set
        {
            this.taxationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("invoice-no")]
    public string invoiceno
    {
        get
        {
            return this.invoicenoField;
        }
        set
        {
            this.invoicenoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("current-order-no")]
    public string currentorderno
    {
        get
        {
            return this.currentordernoField;
        }
        set
        {
            this.currentordernoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer")]
    public ordersOrderCustomer[] customer
    {
        get
        {
            return this.customerField;
        }
        set
        {
            this.customerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("status")]
    public status[] status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("product-lineitems")]
    [System.Xml.Serialization.XmlArrayItemAttribute("product-lineitem", typeof(ordersOrderProductlineitemsProductlineitem), IsNullable = false)]
    public ordersOrderProductlineitemsProductlineitem[] productlineitems
    {
        get
        {
            return this.productlineitemsField;
        }
        set
        {
            this.productlineitemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("shipping-lineitems")]
    [System.Xml.Serialization.XmlArrayItemAttribute("shipping-lineitem", typeof(ordersOrderShippinglineitemsShippinglineitem), IsNullable = false)]
    public ordersOrderShippinglineitemsShippinglineitem[] shippinglineitems
    {
        get
        {
            return this.shippinglineitemsField;
        }
        set
        {
            this.shippinglineitemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("shipment", typeof(ordersOrderShipmentsShipment), IsNullable = false)]
    public ordersOrderShipmentsShipment[] shipments
    {
        get
        {
            return this.shipmentsField;
        }
        set
        {
            this.shipmentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("totals")]
    public totals[] totals
    {
        get
        {
            return this.totalsField;
        }
        set
        {
            this.totalsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("payment", typeof(ordersOrderPaymentsPayment), IsNullable = false)]
    public ordersOrderPaymentsPayment[] payments
    {
        get
        {
            return this.paymentsField;
        }
        set
        {
            this.paymentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("custom-attributes")]
    [System.Xml.Serialization.XmlArrayItemAttribute("custom-attribute", typeof(customattributesCustomattribute))]
    public customattributesCustomattribute[] customattributes
    {
        get
        {
            return this.customattributesField;
        }
        set
        {
            this.customattributesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("order-no")]
    public string orderno
    {
        get
        {
            return this.ordernoField;
        }
        set
        {
            this.ordernoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class ordersOrderCustomer
{

    private string customernameField;

    private string customeremailField;

    private ordersOrderCustomerBillingaddress[] billingaddressField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-name")]
    public string customername
    {
        get
        {
            return this.customernameField;
        }
        set
        {
            this.customernameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-email")]
    public string customeremail
    {
        get
        {
            return this.customeremailField;
        }
        set
        {
            this.customeremailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("billing-address")]
    public ordersOrderCustomerBillingaddress[] billingaddress
    {
        get
        {
            return this.billingaddressField;
        }
        set
        {
            this.billingaddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class ordersOrderCustomerBillingaddress
{

    private string firstnameField;

    private string lastnameField;

    private string address1Field;

    private string cityField;

    private string postalcodeField;

    private string statecodeField;

    private string countrycodeField;

    private string phoneField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("first-name")]
    public string firstname
    {
        get
        {
            return this.firstnameField;
        }
        set
        {
            this.firstnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-name")]
    public string lastname
    {
        get
        {
            return this.lastnameField;
        }
        set
        {
            this.lastnameField = value;
        }
    }

    /// <remarks/>
    public string address1
    {
        get
        {
            return this.address1Field;
        }
        set
        {
            this.address1Field = value;
        }
    }

    /// <remarks/>
    public string city
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("postal-code")]
    public string postalcode
    {
        get
        {
            return this.postalcodeField;
        }
        set
        {
            this.postalcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("state-code")]
    public string statecode
    {
        get
        {
            return this.statecodeField;
        }
        set
        {
            this.statecodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("country-code")]
    public string countrycode
    {
        get
        {
            return this.countrycodeField;
        }
        set
        {
            this.countrycodeField = value;
        }
    }

    /// <remarks/>
    public string phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class ordersOrderProductlineitemsProductlineitem
{

    private string netpriceField;

    private string taxField;

    private string grosspriceField;

    private string basepriceField;

    private string lineitemtextField;

    private string taxbasisField;

    private string positionField;

    private string productidField;

    private string productnameField;

    private string taxrateField;

    private string shipmentidField;

    private string giftField;

    private ordersOrderProductlineitemsProductlineitemQuantity[] quantityField;

    private ordersOrderProductlineitemsProductlineitemOptionlineitemsOptionlineitem[] optionlineitemsField;

    private customattributesCustomattribute[] customattributesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("net-price")]
    public string netprice
    {
        get
        {
            return this.netpriceField;
        }
        set
        {
            this.netpriceField = value;
        }
    }

    /// <remarks/>
    public string tax
    {
        get
        {
            return this.taxField;
        }
        set
        {
            this.taxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gross-price")]
    public string grossprice
    {
        get
        {
            return this.grosspriceField;
        }
        set
        {
            this.grosspriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("base-price")]
    public string baseprice
    {
        get
        {
            return this.basepriceField;
        }
        set
        {
            this.basepriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("lineitem-text")]
    public string lineitemtext
    {
        get
        {
            return this.lineitemtextField;
        }
        set
        {
            this.lineitemtextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tax-basis")]
    public string taxbasis
    {
        get
        {
            return this.taxbasisField;
        }
        set
        {
            this.taxbasisField = value;
        }
    }

    /// <remarks/>
    public string position
    {
        get
        {
            return this.positionField;
        }
        set
        {
            this.positionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("product-id")]
    public string productid
    {
        get
        {
            return this.productidField;
        }
        set
        {
            this.productidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("product-name")]
    public string productname
    {
        get
        {
            return this.productnameField;
        }
        set
        {
            this.productnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tax-rate")]
    public string taxrate
    {
        get
        {
            return this.taxrateField;
        }
        set
        {
            this.taxrateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipment-id")]
    public string shipmentid
    {
        get
        {
            return this.shipmentidField;
        }
        set
        {
            this.shipmentidField = value;
        }
    }

    /// <remarks/>
    public string gift
    {
        get
        {
            return this.giftField;
        }
        set
        {
            this.giftField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quantity", IsNullable = true)]
    public ordersOrderProductlineitemsProductlineitemQuantity[] quantity
    {
        get
        {
            return this.quantityField;
        }
        set
        {
            this.quantityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("option-lineitems")]
    [System.Xml.Serialization.XmlArrayItemAttribute("option-lineitem", typeof(ordersOrderProductlineitemsProductlineitemOptionlineitemsOptionlineitem), IsNullable = false)]
    public ordersOrderProductlineitemsProductlineitemOptionlineitemsOptionlineitem[] optionlineitems
    {
        get
        {
            return this.optionlineitemsField;
        }
        set
        {
            this.optionlineitemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("custom-attributes")]
    [System.Xml.Serialization.XmlArrayItemAttribute("custom-attribute", typeof(customattributesCustomattribute))]
    public customattributesCustomattribute[] customattributes
    {
        get
        {
            return this.customattributesField;
        }
        set
        {
            this.customattributesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class ordersOrderProductlineitemsProductlineitemQuantity
{

    private string unitField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class ordersOrderProductlineitemsProductlineitemOptionlineitemsOptionlineitem
{

    private string netpriceField;

    private string taxField;

    private string grosspriceField;

    private string basepriceField;

    private string lineitemtextField;

    private string taxbasisField;

    private string optionidField;

    private string valueidField;

    private string productidField;

    private customattributesCustomattribute[] customattributesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("net-price")]
    public string netprice
    {
        get
        {
            return this.netpriceField;
        }
        set
        {
            this.netpriceField = value;
        }
    }

    /// <remarks/>
    public string tax
    {
        get
        {
            return this.taxField;
        }
        set
        {
            this.taxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gross-price")]
    public string grossprice
    {
        get
        {
            return this.grosspriceField;
        }
        set
        {
            this.grosspriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("base-price")]
    public string baseprice
    {
        get
        {
            return this.basepriceField;
        }
        set
        {
            this.basepriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("lineitem-text")]
    public string lineitemtext
    {
        get
        {
            return this.lineitemtextField;
        }
        set
        {
            this.lineitemtextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tax-basis")]
    public string taxbasis
    {
        get
        {
            return this.taxbasisField;
        }
        set
        {
            this.taxbasisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-id")]
    public string optionid
    {
        get
        {
            return this.optionidField;
        }
        set
        {
            this.optionidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("value-id")]
    public string valueid
    {
        get
        {
            return this.valueidField;
        }
        set
        {
            this.valueidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("product-id")]
    public string productid
    {
        get
        {
            return this.productidField;
        }
        set
        {
            this.productidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("custom-attributes")]
    [System.Xml.Serialization.XmlArrayItemAttribute("custom-attribute", typeof(customattributesCustomattribute))]
    public customattributesCustomattribute[] customattributes
    {
        get
        {
            return this.customattributesField;
        }
        set
        {
            this.customattributesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class ordersOrderShippinglineitemsShippinglineitem
{

    private string netpriceField;

    private string taxField;

    private string grosspriceField;

    private string basepriceField;

    private string lineitemtextField;

    private string taxbasisField;

    private string itemidField;

    private string shipmentidField;

    private string taxrateField;

    private customattributesCustomattribute[] customattributesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("net-price")]
    public string netprice
    {
        get
        {
            return this.netpriceField;
        }
        set
        {
            this.netpriceField = value;
        }
    }

    /// <remarks/>
    public string tax
    {
        get
        {
            return this.taxField;
        }
        set
        {
            this.taxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gross-price")]
    public string grossprice
    {
        get
        {
            return this.grosspriceField;
        }
        set
        {
            this.grosspriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("base-price")]
    public string baseprice
    {
        get
        {
            return this.basepriceField;
        }
        set
        {
            this.basepriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("lineitem-text")]
    public string lineitemtext
    {
        get
        {
            return this.lineitemtextField;
        }
        set
        {
            this.lineitemtextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tax-basis")]
    public string taxbasis
    {
        get
        {
            return this.taxbasisField;
        }
        set
        {
            this.taxbasisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-id")]
    public string itemid
    {
        get
        {
            return this.itemidField;
        }
        set
        {
            this.itemidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipment-id")]
    public string shipmentid
    {
        get
        {
            return this.shipmentidField;
        }
        set
        {
            this.shipmentidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tax-rate")]
    public string taxrate
    {
        get
        {
            return this.taxrateField;
        }
        set
        {
            this.taxrateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("custom-attributes")]
    [System.Xml.Serialization.XmlArrayItemAttribute("custom-attribute", typeof(customattributesCustomattribute))]
    public customattributesCustomattribute[] customattributes
    {
        get
        {
            return this.customattributesField;
        }
        set
        {
            this.customattributesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class ordersOrderShipmentsShipment
{

    private string shippingmethodField;

    private string giftField;

    private status[] statusField;

    private ordersOrderShipmentsShipmentShippingaddress[] shippingaddressField;

    private totals[] totalsField;

    private customattributesCustomattribute[] customattributesField;

    private string shipmentidField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-method")]
    public string shippingmethod
    {
        get
        {
            return this.shippingmethodField;
        }
        set
        {
            this.shippingmethodField = value;
        }
    }

    /// <remarks/>
    public string gift
    {
        get
        {
            return this.giftField;
        }
        set
        {
            this.giftField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("status")]
    public status[] status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-address")]
    public ordersOrderShipmentsShipmentShippingaddress[] shippingaddress
    {
        get
        {
            return this.shippingaddressField;
        }
        set
        {
            this.shippingaddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("totals")]
    public totals[] totals
    {
        get
        {
            return this.totalsField;
        }
        set
        {
            this.totalsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("custom-attributes")]
    [System.Xml.Serialization.XmlArrayItemAttribute("custom-attribute", typeof(customattributesCustomattribute))]
    public customattributesCustomattribute[] customattributes
    {
        get
        {
            return this.customattributesField;
        }
        set
        {
            this.customattributesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("shipment-id")]
    public string shipmentid
    {
        get
        {
            return this.shipmentidField;
        }
        set
        {
            this.shipmentidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class ordersOrderShipmentsShipmentShippingaddress
{

    private string firstnameField;

    private string lastnameField;

    private string address1Field;

    private string cityField;

    private string postalcodeField;

    private string statecodeField;

    private string countrycodeField;

    private string phoneField;

    private customattributesCustomattribute[] customattributesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("first-name")]
    public string firstname
    {
        get
        {
            return this.firstnameField;
        }
        set
        {
            this.firstnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-name")]
    public string lastname
    {
        get
        {
            return this.lastnameField;
        }
        set
        {
            this.lastnameField = value;
        }
    }

    /// <remarks/>
    public string address1
    {
        get
        {
            return this.address1Field;
        }
        set
        {
            this.address1Field = value;
        }
    }

    /// <remarks/>
    public string city
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("postal-code")]
    public string postalcode
    {
        get
        {
            return this.postalcodeField;
        }
        set
        {
            this.postalcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("state-code")]
    public string statecode
    {
        get
        {
            return this.statecodeField;
        }
        set
        {
            this.statecodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("country-code")]
    public string countrycode
    {
        get
        {
            return this.countrycodeField;
        }
        set
        {
            this.countrycodeField = value;
        }
    }

    /// <remarks/>
    public string phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("custom-attributes")]
    [System.Xml.Serialization.XmlArrayItemAttribute("custom-attribute", typeof(customattributesCustomattribute))]
    public customattributesCustomattribute[] customattributes
    {
        get
        {
            return this.customattributesField;
        }
        set
        {
            this.customattributesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class ordersOrderPaymentsPayment
{

    private string amountField;

    private string processoridField;

    private string transactionidField;

    private ordersOrderPaymentsPaymentCreditcard[] creditcardField;

    private customattributesCustomattribute[] customattributesField;

    /// <remarks/>
    public string amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("processor-id")]
    public string processorid
    {
        get
        {
            return this.processoridField;
        }
        set
        {
            this.processoridField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("transaction-id")]
    public string transactionid
    {
        get
        {
            return this.transactionidField;
        }
        set
        {
            this.transactionidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("credit-card")]
    public ordersOrderPaymentsPaymentCreditcard[] creditcard
    {
        get
        {
            return this.creditcardField;
        }
        set
        {
            this.creditcardField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("custom-attributes")]
    [System.Xml.Serialization.XmlArrayItemAttribute("custom-attribute", typeof(customattributesCustomattribute))]
    public customattributesCustomattribute[] customattributes
    {
        get
        {
            return this.customattributesField;
        }
        set
        {
            this.customattributesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")]
public partial class ordersOrderPaymentsPaymentCreditcard
{

    private string cardtypeField;

    private string cardnumberField;

    private string cardholderField;

    private string expirationmonthField;

    private string expirationyearField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("card-type")]
    public string cardtype
    {
        get
        {
            return this.cardtypeField;
        }
        set
        {
            this.cardtypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("card-number")]
    public string cardnumber
    {
        get
        {
            return this.cardnumberField;
        }
        set
        {
            this.cardnumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("card-holder")]
    public string cardholder
    {
        get
        {
            return this.cardholderField;
        }
        set
        {
            this.cardholderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expiration-month")]
    public string expirationmonth
    {
        get
        {
            return this.expirationmonthField;
        }
        set
        {
            this.expirationmonthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expiration-year")]
    public string expirationyear
    {
        get
        {
            return this.expirationyearField;
        }
        set
        {
            this.expirationyearField = value;
        }
    }
}
